name: "CI/CD Pipeline for LMS Front-End"
on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3

      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: 18

      
      - name: Installing SASS
        run: npm i -g sass 

      - name: Compiling scss to css
        run: sass scss:css

      - name: Zipping to deploy
        run: zip -r dist.zip css page js index.html

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}'

      - name: 'Setting up gcloud'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Deploying the Zip
        run: gcloud compute scp --zone="asia-south1-a" dist.zip root@dep-9-vm:/opt/apache/apache-tomcat-10.1.1/webapps/lms

      - name: Clean up old stuff
        run: >
          gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
          --command="sudo rm -rf "opt/apache/apache-tomcat-10.1.1/webapps/lms/css 
          --command="sudo rm -rf "opt/apache/apache-tomcat-10.1.1/webapps/lms/page 
          --command="sudo rm -rf "opt/apache/apache-tomcat-10.1.1/webapps/lms/js 
          --command="sudo rm -rf "opt/apache/apache-tomcat-10.1.1/webapps/lms/index.html
          "

      - name: Extraction the Zip
        run: >
          gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
          --command="sudo unzip opt/apache/apache-tomcat-10.1.1/webapps/lms/dist.zip /opt/apache/apache-tomcat-10.1.1/webapps/lms"
        
      - name: Cleaning the leftover
        run: >
          gcloud compute ssh --zone="asia-south1-a" dep-9-vm 
          --command="sudo rm opt/apache/apache-tomcat-10.1.1/webapps/lms/dist.zip "
